module.exports = {
  name: 'flip',
  check: (msg) => /\bflip\b/i.test(msg.content),
  execute: (msg) => {
    const replies = [
      '🐷 HogBot flipped and landed upright!',
      '🐷 HogBot flipped but tumbled onto his side.',
      '🐷 HogBot sprung into the air and stuck the landing!',
      '🐷 HogBot tried a flip and ended up face-planting.',
      '🐷 HogBot somersaulted gracefully!',
      '🐷 HogBot tripped mid-air and flopped over.',
      '🐷 HogBot spun around and landed on his hooves!',
      '🐷 HogBot over-rotated and crashed to the ground.',
      '🐷 HogBot nailed a perfect front flip!',
      '🐷 HogBot miscalculated and belly-flopped.',
      '🐷 HogBot executed a stylish backflip!',
      '🐷 HogBot landed awkwardly but recovered.',
      '🐷 HogBot leapt high and stuck the landing!',
      '🐷 HogBot’s flip ended with a graceful bow.',
      '🐷 HogBot slipped and rolled instead of flipping.',
      '🐷 HogBot cleared the bar and landed perfectly!',
      '🐷 HogBot lost balance and wobbled on landing.',
      '🐷 HogBot popped a quick flip and held it!',
      '🐷 HogBot went wide and ended on his belly.',
      '🐷 HogBot tucked and rolled like a pro!',
      '🐷 HogBot misjudged the jump and stumbled.',
      '🐷 HogBot’s hooves touched down cleanly!',
      '🐷 HogBot belly-flopped with comic flair.',
      '🐷 HogBot twirled and stuck the stunt!',
      '🐷 HogBot landed hard but shook it off.',
      '🐷 HogBot nailed a double flip!',
      '🐷 HogBot tripped over and rolled away.',
      '🐷 HogBot’s flip was textbook perfection!',
      '🐷 HogBot slipped and rolled to safety.',
      '🐷 HogBot soared and landed like a champion!',
      '🐷 HogBot flopped gracelessly but laughed it off.',
      '🐷 HogBot spun three times and nailed it!',
      '🐷 HogBot misstepped and slid on his side.',
      '🐷 HogBot spun elegantly and finished strong.',
      '🐷 HogBot’s flip ended in a pratfall.',
      '🐷 HogBot went airborne and stuck it!',
      '🐷 HogBot tumbled out of the flip, still cute.',
      '🐷 HogBot sprang up and landed with flair!',
      '🐷 HogBot’s hooves slipped, but he recovered mid-roll.',
      '🐷 HogBot executed a flawless corkscrew!',
      '🐷 HogBot ended flat on his back.',
      '🐷 HogBot’s flip was on point!',
      '🐷 HogBot wobbled but kept upright.',
      '🐷 HogBot’s aerial twist was magnificent!',
      '🐷 HogBot’s landing was more flop than flip.',
      '🐷 HogBot stuck the split-leg landing!',
      '🐷 HogBot slipped but rolled to a stand.',
      '🐷 HogBot’s gymnastic pig move impressed all!',
      '🐷 HogBot sank in the mud mid-flip.',
      '🐷 HogBot leapt, flipped, and turned a headstand!',
      '🐷 HogBot’s flip ended in a dainty curtsy.',
      '🐷 HogBot misfired and did a belly roll.',
      '🐷 HogBot soared and landed like a feather!',
      '🐷 HogBot spun out of control and laughed.',
      '🐷 HogBot performed a perfect cartwheel instead!',
      '🐷 HogBot’s flip was Oscar-worthy!',
      '🐷 HogBot slipped with mud, still smiling!',
      '🐷 HogBot’s double backflip was insane!',
      '🐷 HogBot’s landing was more graceful than expected.',
      '🐷 HogBot’s flop looked like a comedy sketch.',
      '🐷 HogBot stuck the stunt, crowd goes oink!',
      '🐷 HogBot missed the mat and slid away.',
      '🐷 HogBot’s flip looked like poetry in motion.',
      '🐷 HogBot ended in a glorious belly flop.',
      '🐷 HogBot’s pirouette-to-flip was next level!',
      '🐷 HogBot’s landing was a bit wobbly but triumphant.',
      '🐷 HogBot’s flop turned into a somersault!',
      '🐷 HogBot’s flip was magical!',
      '🐷 HogBot’s slip was still adorable!',
      '🐷 HogBot handled that stunt like a pro!',
      '🐷 HogBot’s flop looked intentional.',
      '🐷 HogBot wowed everyone with that flip!',
      '🐷 HogBot’s tumble was theatrical!',
      '🐷 HogBot’s perfect landing stole the show!',
      '🐷 HogBot’s flop was meme-worthy.',
      '🐷 HogBot’s midair spin was breathtaking!',
      '🐷 HogBot’s flop ended in giggles.',
      '🐷 HogBot’s flip defied gravity!',
      '🐷 HogBot’s awkward landing was too funny!',
      '🐷 HogBot landed on his feet and took a bow!',
      '🐷 HogBot ended in a somersault finale!',
      '🐷 HogBot’s flip was legendary!',
      '🐷 HogBot’s bunny hop was unexpected!',
      '🐷 HogBot’s final flop was glorious!',
      '🐷 HogBot’s heroic flip went viral!',
      '🐷 HogBot’s landing was pig-perfect!',
      '🐷 HogBot’s flop got a standing oinkation!',
      '🐷 HogBot soared, flipped, and won hearts!',
      '🐷 HogBot’s flip was the highlight of the day!',
      '🐷 HogBot’s flop was captured for eternity!',
      '🐷 HogBot’s impeccable landing wowed everyone!',
      '🐷 HogBot’s tumble was pure comedy gold!',
      '🐷 HogBot’s flip was... well, hog-tastic!',
      '🐷 HogBot’s flop was adorable chaos!',
      '🐷 HogBot’s landing was a muddy masterpiece!',
      '🐷 HogBot’s flip earned a spot on highlights!',
      '🐷 HogBot’s flop turned into a dance move!',
      '🐷 HogBot attempted a somersault but ended in a piggy puddle!',
      '🐷 HogBot sprang up, flipped, and snorted mid-air!',
      '🐷 HogBot launched a backflip that echoed like thunder!',
      '🐷 HogBot’s hooves hit the ground with a squealy flourish!',
      '🐷 HogBot moonwalked after the flip, so smooth!',
      '🐷 HogBot’s flip ended in a jubilant oink celebration!',
      '🐷 HogBot tried a triple twist and invented a new move!',
      '🐷 HogBot’s flip turned into an impressive cartwheel!',
      '🐷 HogBot paused mid-flip and nodded at the audience!',
      '🐷 HogBot flipped... into a muddy somersault!',
      '🐷 HogBot’s aerial spin looked like a pig tornado!',
      '🐷 HogBot stuck a ninja star landing!',
      '🐷 HogBot floated like a feather and landed softly!',
      '🐷 HogBot’s flip looked like a ballet pirouette!',
      '🐷 HogBot’s flop created a muddy splash art!',
      '🐷 HogBot twisted and landed with a triumphant grunt!',
      '🐷 HogBot landed so perfectly the ground shook!',
      '🐷 HogBot flailed mid-air but recovered gracefully!',
      '🐷 HogBot’s flip ended in a perfect headstand!',
      '🐷 HogBot spun like a record and scratched a beat!',
      '🐷 HogBot flipped then did a stylish piggy strut!',
      '🐷 HogBot’s landing was so soft it tickled!',
      '🐷 HogBot’s flop looked like a pancake!',
      '🐷 HogBot rebounded off the ground and bounced back up!',
      '🐷 HogBot’s backflip sent him tumbling backward!',
      '🐷 HogBot’s flip dissolved into a hilarious belly roll!',
      '🐷 HogBot’s graceful flip earned a standing oink!',
      '🐷 HogBot’s flip ended with a playful snort!',
      '🐷 HogBot nailed a zero-gravity hover before landing!',
      '🐷 HogBot’s flop resembled a falling feather!',
      '🐷 HogBot’s flip defied physics for a moment!',
      '🐷 HogBot concluded with a piglet-like squeal!',
      '🐷 HogBot’s elegant flip turned into a dramatic pose!',
      '🐷 HogBot’s flop was so epic it echoed!',
      '🐷 HogBot’s midair spin was seamless!',
      '🐷 HogBot pirouetted then kissed the ground!',
      '🐷 HogBot drifted sideways and skidded to a halt!',
      '🐷 HogBot’s flip looked like a circus act!',
      '🐷 HogBot ended the flip with a theatrical bow!',
      '🐷 HogBot’s flop was recorded for piggy posterity!',
      '🐷 HogBot’s flip clipped the breeze with his snout!',
      '🐷 HogBot’s hoof landed perfectly on a leaf!',
      '🐷 HogBot’s stationary flip surprised everyone!',
      '🐷 HogBot spun twice, landed, and winked!',
      '🐷 HogBot bounced on his tail after the flip!',
      '🐷 HogBot’s flip included a mid-air wiggle!',
      '🐷 HogBot ended in a dramatic slide!',
      '🐷 HogBot’s flip turned into an accidental somersault!',
      '🐷 HogBot’s impeccable timing stole the show!',
      '🐷 HogBot’s flop was so graceful it was art!',
      '🐷 HogBot’s midair twist dazzled the crowd!',
      '🐷 HogBot landed and performed a victory dance!',
      '🐷 HogBot’s flip was faster than a blink!',
      '🐷 HogBot’s flop looked like a gentle hug to the dirt!',
      '🐷 HogBot’s aerial corkscrew was flawless!',
      '🐷 HogBot landed on one hoof and balanced!',
      '🐷 HogBot spun off the cliff of excitement!',
      '🐷 HogBot’s flip was so good he squealed!',
      '🐷 HogBot’s flop turned into a playful roll!',
      '🐷 HogBot executed a mid-air twirl before landing!',
      '🐷 HogBot’s final pose was picture-perfect!',
      '🐷 HogBot’s flop echoed across the barn!',
      '🐷 HogBot glided to a halt like a pro skater!',
      '🐷 HogBot whipped out a salute post-flip!',
      '🐷 HogBot’s flip ended in a triumphant snort!',
      '🐷 HogBot’s flop was softer than a cloud!',
      '🐷 HogBot’s jump turned into a majestic flip!',
      '🐷 HogBot’s flop was as funny as it was epic!',
      '🐷 HogBot spun like a top and landed smooth!',
      '🐷 HogBot’s flop created a ripple in the mud!',
      '🐷 HogBot’s flip ended with flourish and fanfare!',
      '🐷 HogBot landed so hard he left hoofprints!',
      '🐷 HogBot’s midair flip looked like a rainbow!',
      '🐷 HogBot landed in a perfect squat!',
      '🐷 HogBot’s flop was the highlight of the pen!',
      '🐷 HogBot’s flip turned into a friendly wave!',
      '🐷 HogBot executed a somersault-to-salute!',
      '🐷 HogBot’s flop was followed by a laugh!',
      '🐷 HogBot’s flip was like a dance of dedication!',
      '🐷 HogBot ended in a dramatic slow-motion flop!',
      '🐷 HogBot’s graceful flop was still adorable!',
      '🐷 HogBot’s flip turned heads in amazement!',
      '🐷 HogBot’s flop was so cute you couldn’t stop smiling!',
      '🐷 HogBot ended his flip with a triumphant snout-raise!',
      '🐷 HogBot’s flop was the talk of the sty!',
      '🐷 HogBot’s flip ended in a celebratory wiggle!',
      '🐷 HogBot fell into a perfect front roll!',
      '🐷 HogBot’s flop was an artistic spectacle!',
      '🐷 HogBot’s flip concluded with a piggy grin!',
      '🐷 HogBot ended in a muddy belly wink!',
      `🐷In the 80s, there was Cold War drama
        We fought the Commies inside Nicaragua
        Our friends were the Contras, freedom was their mantra
        So we sent them lots of money for guns and landmines
        But Congress stopped the Contra money flow
        Just 'cause they moved a teeny bit of blow
        But then a hero came forth, his name was Oliver North
        He and Reagan went around the sissy Congress
        Ollie North
        Ollie North
        You see, North secretly sold missiles to a harmless country called Iran, who would always be a grateful ally
        Then he gave the profits to the Contras
        Genius
        But the sales were uncovered by the press
        Reagan and North began to stress
        'Cause what they did was technically high treason
        But it was totally justified
        North volunteered to take the blame
        To save Reagan from prison rape shame
        The truth he did bury with his hot secretary
        Thanks to her shredder, he got off totally scot-free
        Ollie North
        Ollie North
        He's a soldier
        And a hero
        And a novelist
        And now he's on FOX News`
    ];
    const reply = replies[Math.floor(Math.random() * replies.length)];
    return msg.channel.send(reply);
  }
};
